/* soapCredentialBindingProxy.h
   Generated by gSOAP 2.8.114 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapCredentialBindingProxy_H
#define soapCredentialBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC CredentialBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'CredentialBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvif.h, if any
        /// Construct a proxy with new managing context
        CredentialBindingProxy();
        /// Copy constructor
        CredentialBindingProxy(const CredentialBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        CredentialBindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        CredentialBindingProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        CredentialBindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        CredentialBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        CredentialBindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        CredentialBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~CredentialBindingProxy();
        /// Initializer used by constructors
        virtual void CredentialBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual CredentialBindingProxy *copy();
        /// Copy assignment
        CredentialBindingProxy& operator=(const CredentialBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct wsdd__AppSequenceType *wsdd__AppSequence, struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'GetServiceCapabilities' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetServiceCapabilities(_ns5__GetServiceCapabilities *ns5__GetServiceCapabilities, _ns5__GetServiceCapabilitiesResponse &ns5__GetServiceCapabilitiesResponse) { return this->GetServiceCapabilities(NULL, NULL, ns5__GetServiceCapabilities, ns5__GetServiceCapabilitiesResponse); }
        /// Web service synchronous operation 'GetServiceCapabilities' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetServiceCapabilities(const char *soap_endpoint_url, const char *soap_action, _ns5__GetServiceCapabilities *ns5__GetServiceCapabilities, _ns5__GetServiceCapabilitiesResponse &ns5__GetServiceCapabilitiesResponse) { return this->send_GetServiceCapabilities(soap_endpoint_url, soap_action, ns5__GetServiceCapabilities) || this->recv_GetServiceCapabilities(ns5__GetServiceCapabilitiesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetServiceCapabilities' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetServiceCapabilities(const char *soap_endpoint_url, const char *soap_action, _ns5__GetServiceCapabilities *ns5__GetServiceCapabilities);
        /// Web service asynchronous operation 'recv_GetServiceCapabilities' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetServiceCapabilities(_ns5__GetServiceCapabilitiesResponse &ns5__GetServiceCapabilitiesResponse);
        //
        /// Web service synchronous operation 'GetSupportedFormatTypes' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetSupportedFormatTypes(_ns5__GetSupportedFormatTypes *ns5__GetSupportedFormatTypes, _ns5__GetSupportedFormatTypesResponse &ns5__GetSupportedFormatTypesResponse) { return this->GetSupportedFormatTypes(NULL, NULL, ns5__GetSupportedFormatTypes, ns5__GetSupportedFormatTypesResponse); }
        /// Web service synchronous operation 'GetSupportedFormatTypes' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetSupportedFormatTypes(const char *soap_endpoint_url, const char *soap_action, _ns5__GetSupportedFormatTypes *ns5__GetSupportedFormatTypes, _ns5__GetSupportedFormatTypesResponse &ns5__GetSupportedFormatTypesResponse) { return this->send_GetSupportedFormatTypes(soap_endpoint_url, soap_action, ns5__GetSupportedFormatTypes) || this->recv_GetSupportedFormatTypes(ns5__GetSupportedFormatTypesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetSupportedFormatTypes' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetSupportedFormatTypes(const char *soap_endpoint_url, const char *soap_action, _ns5__GetSupportedFormatTypes *ns5__GetSupportedFormatTypes);
        /// Web service asynchronous operation 'recv_GetSupportedFormatTypes' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetSupportedFormatTypes(_ns5__GetSupportedFormatTypesResponse &ns5__GetSupportedFormatTypesResponse);
        //
        /// Web service synchronous operation 'GetCredentialInfo' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentialInfo(_ns5__GetCredentialInfo *ns5__GetCredentialInfo, _ns5__GetCredentialInfoResponse &ns5__GetCredentialInfoResponse) { return this->GetCredentialInfo(NULL, NULL, ns5__GetCredentialInfo, ns5__GetCredentialInfoResponse); }
        /// Web service synchronous operation 'GetCredentialInfo' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentialInfo(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentialInfo *ns5__GetCredentialInfo, _ns5__GetCredentialInfoResponse &ns5__GetCredentialInfoResponse) { return this->send_GetCredentialInfo(soap_endpoint_url, soap_action, ns5__GetCredentialInfo) || this->recv_GetCredentialInfo(ns5__GetCredentialInfoResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetCredentialInfo' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetCredentialInfo(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentialInfo *ns5__GetCredentialInfo);
        /// Web service asynchronous operation 'recv_GetCredentialInfo' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetCredentialInfo(_ns5__GetCredentialInfoResponse &ns5__GetCredentialInfoResponse);
        //
        /// Web service synchronous operation 'GetCredentialInfoList' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentialInfoList(_ns5__GetCredentialInfoList *ns5__GetCredentialInfoList, _ns5__GetCredentialInfoListResponse &ns5__GetCredentialInfoListResponse) { return this->GetCredentialInfoList(NULL, NULL, ns5__GetCredentialInfoList, ns5__GetCredentialInfoListResponse); }
        /// Web service synchronous operation 'GetCredentialInfoList' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentialInfoList(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentialInfoList *ns5__GetCredentialInfoList, _ns5__GetCredentialInfoListResponse &ns5__GetCredentialInfoListResponse) { return this->send_GetCredentialInfoList(soap_endpoint_url, soap_action, ns5__GetCredentialInfoList) || this->recv_GetCredentialInfoList(ns5__GetCredentialInfoListResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetCredentialInfoList' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetCredentialInfoList(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentialInfoList *ns5__GetCredentialInfoList);
        /// Web service asynchronous operation 'recv_GetCredentialInfoList' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetCredentialInfoList(_ns5__GetCredentialInfoListResponse &ns5__GetCredentialInfoListResponse);
        //
        /// Web service synchronous operation 'GetCredentials' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentials(_ns5__GetCredentials *ns5__GetCredentials, _ns5__GetCredentialsResponse &ns5__GetCredentialsResponse) { return this->GetCredentials(NULL, NULL, ns5__GetCredentials, ns5__GetCredentialsResponse); }
        /// Web service synchronous operation 'GetCredentials' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentials(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentials *ns5__GetCredentials, _ns5__GetCredentialsResponse &ns5__GetCredentialsResponse) { return this->send_GetCredentials(soap_endpoint_url, soap_action, ns5__GetCredentials) || this->recv_GetCredentials(ns5__GetCredentialsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetCredentials' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetCredentials(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentials *ns5__GetCredentials);
        /// Web service asynchronous operation 'recv_GetCredentials' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetCredentials(_ns5__GetCredentialsResponse &ns5__GetCredentialsResponse);
        //
        /// Web service synchronous operation 'GetCredentialList' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentialList(_ns5__GetCredentialList *ns5__GetCredentialList, _ns5__GetCredentialListResponse &ns5__GetCredentialListResponse) { return this->GetCredentialList(NULL, NULL, ns5__GetCredentialList, ns5__GetCredentialListResponse); }
        /// Web service synchronous operation 'GetCredentialList' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentialList(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentialList *ns5__GetCredentialList, _ns5__GetCredentialListResponse &ns5__GetCredentialListResponse) { return this->send_GetCredentialList(soap_endpoint_url, soap_action, ns5__GetCredentialList) || this->recv_GetCredentialList(ns5__GetCredentialListResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetCredentialList' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetCredentialList(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentialList *ns5__GetCredentialList);
        /// Web service asynchronous operation 'recv_GetCredentialList' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetCredentialList(_ns5__GetCredentialListResponse &ns5__GetCredentialListResponse);
        //
        /// Web service synchronous operation 'CreateCredential' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int CreateCredential(_ns5__CreateCredential *ns5__CreateCredential, _ns5__CreateCredentialResponse &ns5__CreateCredentialResponse) { return this->CreateCredential(NULL, NULL, ns5__CreateCredential, ns5__CreateCredentialResponse); }
        /// Web service synchronous operation 'CreateCredential' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int CreateCredential(const char *soap_endpoint_url, const char *soap_action, _ns5__CreateCredential *ns5__CreateCredential, _ns5__CreateCredentialResponse &ns5__CreateCredentialResponse) { return this->send_CreateCredential(soap_endpoint_url, soap_action, ns5__CreateCredential) || this->recv_CreateCredential(ns5__CreateCredentialResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_CreateCredential' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_CreateCredential(const char *soap_endpoint_url, const char *soap_action, _ns5__CreateCredential *ns5__CreateCredential);
        /// Web service asynchronous operation 'recv_CreateCredential' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_CreateCredential(_ns5__CreateCredentialResponse &ns5__CreateCredentialResponse);
        //
        /// Web service synchronous operation 'SetCredential' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetCredential(_ns5__SetCredential *ns5__SetCredential, _ns5__SetCredentialResponse &ns5__SetCredentialResponse) { return this->SetCredential(NULL, NULL, ns5__SetCredential, ns5__SetCredentialResponse); }
        /// Web service synchronous operation 'SetCredential' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetCredential(const char *soap_endpoint_url, const char *soap_action, _ns5__SetCredential *ns5__SetCredential, _ns5__SetCredentialResponse &ns5__SetCredentialResponse) { return this->send_SetCredential(soap_endpoint_url, soap_action, ns5__SetCredential) || this->recv_SetCredential(ns5__SetCredentialResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetCredential' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetCredential(const char *soap_endpoint_url, const char *soap_action, _ns5__SetCredential *ns5__SetCredential);
        /// Web service asynchronous operation 'recv_SetCredential' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetCredential(_ns5__SetCredentialResponse &ns5__SetCredentialResponse);
        //
        /// Web service synchronous operation 'ModifyCredential' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int ModifyCredential(_ns5__ModifyCredential *ns5__ModifyCredential, _ns5__ModifyCredentialResponse &ns5__ModifyCredentialResponse) { return this->ModifyCredential(NULL, NULL, ns5__ModifyCredential, ns5__ModifyCredentialResponse); }
        /// Web service synchronous operation 'ModifyCredential' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int ModifyCredential(const char *soap_endpoint_url, const char *soap_action, _ns5__ModifyCredential *ns5__ModifyCredential, _ns5__ModifyCredentialResponse &ns5__ModifyCredentialResponse) { return this->send_ModifyCredential(soap_endpoint_url, soap_action, ns5__ModifyCredential) || this->recv_ModifyCredential(ns5__ModifyCredentialResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_ModifyCredential' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_ModifyCredential(const char *soap_endpoint_url, const char *soap_action, _ns5__ModifyCredential *ns5__ModifyCredential);
        /// Web service asynchronous operation 'recv_ModifyCredential' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_ModifyCredential(_ns5__ModifyCredentialResponse &ns5__ModifyCredentialResponse);
        //
        /// Web service synchronous operation 'DeleteCredential' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCredential(_ns5__DeleteCredential *ns5__DeleteCredential, _ns5__DeleteCredentialResponse &ns5__DeleteCredentialResponse) { return this->DeleteCredential(NULL, NULL, ns5__DeleteCredential, ns5__DeleteCredentialResponse); }
        /// Web service synchronous operation 'DeleteCredential' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCredential(const char *soap_endpoint_url, const char *soap_action, _ns5__DeleteCredential *ns5__DeleteCredential, _ns5__DeleteCredentialResponse &ns5__DeleteCredentialResponse) { return this->send_DeleteCredential(soap_endpoint_url, soap_action, ns5__DeleteCredential) || this->recv_DeleteCredential(ns5__DeleteCredentialResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteCredential' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteCredential(const char *soap_endpoint_url, const char *soap_action, _ns5__DeleteCredential *ns5__DeleteCredential);
        /// Web service asynchronous operation 'recv_DeleteCredential' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteCredential(_ns5__DeleteCredentialResponse &ns5__DeleteCredentialResponse);
        //
        /// Web service synchronous operation 'GetCredentialState' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentialState(_ns5__GetCredentialState *ns5__GetCredentialState, _ns5__GetCredentialStateResponse &ns5__GetCredentialStateResponse) { return this->GetCredentialState(NULL, NULL, ns5__GetCredentialState, ns5__GetCredentialStateResponse); }
        /// Web service synchronous operation 'GetCredentialState' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentialState(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentialState *ns5__GetCredentialState, _ns5__GetCredentialStateResponse &ns5__GetCredentialStateResponse) { return this->send_GetCredentialState(soap_endpoint_url, soap_action, ns5__GetCredentialState) || this->recv_GetCredentialState(ns5__GetCredentialStateResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetCredentialState' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetCredentialState(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentialState *ns5__GetCredentialState);
        /// Web service asynchronous operation 'recv_GetCredentialState' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetCredentialState(_ns5__GetCredentialStateResponse &ns5__GetCredentialStateResponse);
        //
        /// Web service synchronous operation 'EnableCredential' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int EnableCredential(_ns5__EnableCredential *ns5__EnableCredential, _ns5__EnableCredentialResponse &ns5__EnableCredentialResponse) { return this->EnableCredential(NULL, NULL, ns5__EnableCredential, ns5__EnableCredentialResponse); }
        /// Web service synchronous operation 'EnableCredential' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int EnableCredential(const char *soap_endpoint_url, const char *soap_action, _ns5__EnableCredential *ns5__EnableCredential, _ns5__EnableCredentialResponse &ns5__EnableCredentialResponse) { return this->send_EnableCredential(soap_endpoint_url, soap_action, ns5__EnableCredential) || this->recv_EnableCredential(ns5__EnableCredentialResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_EnableCredential' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_EnableCredential(const char *soap_endpoint_url, const char *soap_action, _ns5__EnableCredential *ns5__EnableCredential);
        /// Web service asynchronous operation 'recv_EnableCredential' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_EnableCredential(_ns5__EnableCredentialResponse &ns5__EnableCredentialResponse);
        //
        /// Web service synchronous operation 'DisableCredential' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DisableCredential(_ns5__DisableCredential *ns5__DisableCredential, _ns5__DisableCredentialResponse &ns5__DisableCredentialResponse) { return this->DisableCredential(NULL, NULL, ns5__DisableCredential, ns5__DisableCredentialResponse); }
        /// Web service synchronous operation 'DisableCredential' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DisableCredential(const char *soap_endpoint_url, const char *soap_action, _ns5__DisableCredential *ns5__DisableCredential, _ns5__DisableCredentialResponse &ns5__DisableCredentialResponse) { return this->send_DisableCredential(soap_endpoint_url, soap_action, ns5__DisableCredential) || this->recv_DisableCredential(ns5__DisableCredentialResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DisableCredential' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DisableCredential(const char *soap_endpoint_url, const char *soap_action, _ns5__DisableCredential *ns5__DisableCredential);
        /// Web service asynchronous operation 'recv_DisableCredential' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DisableCredential(_ns5__DisableCredentialResponse &ns5__DisableCredentialResponse);
        //
        /// Web service synchronous operation 'ResetAntipassbackViolation' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int ResetAntipassbackViolation(_ns5__ResetAntipassbackViolation *ns5__ResetAntipassbackViolation, _ns5__ResetAntipassbackViolationResponse &ns5__ResetAntipassbackViolationResponse) { return this->ResetAntipassbackViolation(NULL, NULL, ns5__ResetAntipassbackViolation, ns5__ResetAntipassbackViolationResponse); }
        /// Web service synchronous operation 'ResetAntipassbackViolation' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int ResetAntipassbackViolation(const char *soap_endpoint_url, const char *soap_action, _ns5__ResetAntipassbackViolation *ns5__ResetAntipassbackViolation, _ns5__ResetAntipassbackViolationResponse &ns5__ResetAntipassbackViolationResponse) { return this->send_ResetAntipassbackViolation(soap_endpoint_url, soap_action, ns5__ResetAntipassbackViolation) || this->recv_ResetAntipassbackViolation(ns5__ResetAntipassbackViolationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_ResetAntipassbackViolation' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_ResetAntipassbackViolation(const char *soap_endpoint_url, const char *soap_action, _ns5__ResetAntipassbackViolation *ns5__ResetAntipassbackViolation);
        /// Web service asynchronous operation 'recv_ResetAntipassbackViolation' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_ResetAntipassbackViolation(_ns5__ResetAntipassbackViolationResponse &ns5__ResetAntipassbackViolationResponse);
        //
        /// Web service synchronous operation 'GetCredentialIdentifiers' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentialIdentifiers(_ns5__GetCredentialIdentifiers *ns5__GetCredentialIdentifiers, _ns5__GetCredentialIdentifiersResponse &ns5__GetCredentialIdentifiersResponse) { return this->GetCredentialIdentifiers(NULL, NULL, ns5__GetCredentialIdentifiers, ns5__GetCredentialIdentifiersResponse); }
        /// Web service synchronous operation 'GetCredentialIdentifiers' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentialIdentifiers(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentialIdentifiers *ns5__GetCredentialIdentifiers, _ns5__GetCredentialIdentifiersResponse &ns5__GetCredentialIdentifiersResponse) { return this->send_GetCredentialIdentifiers(soap_endpoint_url, soap_action, ns5__GetCredentialIdentifiers) || this->recv_GetCredentialIdentifiers(ns5__GetCredentialIdentifiersResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetCredentialIdentifiers' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetCredentialIdentifiers(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentialIdentifiers *ns5__GetCredentialIdentifiers);
        /// Web service asynchronous operation 'recv_GetCredentialIdentifiers' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetCredentialIdentifiers(_ns5__GetCredentialIdentifiersResponse &ns5__GetCredentialIdentifiersResponse);
        //
        /// Web service synchronous operation 'SetCredentialIdentifier' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetCredentialIdentifier(_ns5__SetCredentialIdentifier *ns5__SetCredentialIdentifier, _ns5__SetCredentialIdentifierResponse &ns5__SetCredentialIdentifierResponse) { return this->SetCredentialIdentifier(NULL, NULL, ns5__SetCredentialIdentifier, ns5__SetCredentialIdentifierResponse); }
        /// Web service synchronous operation 'SetCredentialIdentifier' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetCredentialIdentifier(const char *soap_endpoint_url, const char *soap_action, _ns5__SetCredentialIdentifier *ns5__SetCredentialIdentifier, _ns5__SetCredentialIdentifierResponse &ns5__SetCredentialIdentifierResponse) { return this->send_SetCredentialIdentifier(soap_endpoint_url, soap_action, ns5__SetCredentialIdentifier) || this->recv_SetCredentialIdentifier(ns5__SetCredentialIdentifierResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetCredentialIdentifier' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetCredentialIdentifier(const char *soap_endpoint_url, const char *soap_action, _ns5__SetCredentialIdentifier *ns5__SetCredentialIdentifier);
        /// Web service asynchronous operation 'recv_SetCredentialIdentifier' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetCredentialIdentifier(_ns5__SetCredentialIdentifierResponse &ns5__SetCredentialIdentifierResponse);
        //
        /// Web service synchronous operation 'DeleteCredentialIdentifier' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCredentialIdentifier(_ns5__DeleteCredentialIdentifier *ns5__DeleteCredentialIdentifier, _ns5__DeleteCredentialIdentifierResponse &ns5__DeleteCredentialIdentifierResponse) { return this->DeleteCredentialIdentifier(NULL, NULL, ns5__DeleteCredentialIdentifier, ns5__DeleteCredentialIdentifierResponse); }
        /// Web service synchronous operation 'DeleteCredentialIdentifier' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCredentialIdentifier(const char *soap_endpoint_url, const char *soap_action, _ns5__DeleteCredentialIdentifier *ns5__DeleteCredentialIdentifier, _ns5__DeleteCredentialIdentifierResponse &ns5__DeleteCredentialIdentifierResponse) { return this->send_DeleteCredentialIdentifier(soap_endpoint_url, soap_action, ns5__DeleteCredentialIdentifier) || this->recv_DeleteCredentialIdentifier(ns5__DeleteCredentialIdentifierResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteCredentialIdentifier' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteCredentialIdentifier(const char *soap_endpoint_url, const char *soap_action, _ns5__DeleteCredentialIdentifier *ns5__DeleteCredentialIdentifier);
        /// Web service asynchronous operation 'recv_DeleteCredentialIdentifier' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteCredentialIdentifier(_ns5__DeleteCredentialIdentifierResponse &ns5__DeleteCredentialIdentifierResponse);
        //
        /// Web service synchronous operation 'GetCredentialAccessProfiles' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentialAccessProfiles(_ns5__GetCredentialAccessProfiles *ns5__GetCredentialAccessProfiles, _ns5__GetCredentialAccessProfilesResponse &ns5__GetCredentialAccessProfilesResponse) { return this->GetCredentialAccessProfiles(NULL, NULL, ns5__GetCredentialAccessProfiles, ns5__GetCredentialAccessProfilesResponse); }
        /// Web service synchronous operation 'GetCredentialAccessProfiles' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetCredentialAccessProfiles(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentialAccessProfiles *ns5__GetCredentialAccessProfiles, _ns5__GetCredentialAccessProfilesResponse &ns5__GetCredentialAccessProfilesResponse) { return this->send_GetCredentialAccessProfiles(soap_endpoint_url, soap_action, ns5__GetCredentialAccessProfiles) || this->recv_GetCredentialAccessProfiles(ns5__GetCredentialAccessProfilesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetCredentialAccessProfiles' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetCredentialAccessProfiles(const char *soap_endpoint_url, const char *soap_action, _ns5__GetCredentialAccessProfiles *ns5__GetCredentialAccessProfiles);
        /// Web service asynchronous operation 'recv_GetCredentialAccessProfiles' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetCredentialAccessProfiles(_ns5__GetCredentialAccessProfilesResponse &ns5__GetCredentialAccessProfilesResponse);
        //
        /// Web service synchronous operation 'SetCredentialAccessProfiles' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetCredentialAccessProfiles(_ns5__SetCredentialAccessProfiles *ns5__SetCredentialAccessProfiles, _ns5__SetCredentialAccessProfilesResponse &ns5__SetCredentialAccessProfilesResponse) { return this->SetCredentialAccessProfiles(NULL, NULL, ns5__SetCredentialAccessProfiles, ns5__SetCredentialAccessProfilesResponse); }
        /// Web service synchronous operation 'SetCredentialAccessProfiles' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetCredentialAccessProfiles(const char *soap_endpoint_url, const char *soap_action, _ns5__SetCredentialAccessProfiles *ns5__SetCredentialAccessProfiles, _ns5__SetCredentialAccessProfilesResponse &ns5__SetCredentialAccessProfilesResponse) { return this->send_SetCredentialAccessProfiles(soap_endpoint_url, soap_action, ns5__SetCredentialAccessProfiles) || this->recv_SetCredentialAccessProfiles(ns5__SetCredentialAccessProfilesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetCredentialAccessProfiles' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetCredentialAccessProfiles(const char *soap_endpoint_url, const char *soap_action, _ns5__SetCredentialAccessProfiles *ns5__SetCredentialAccessProfiles);
        /// Web service asynchronous operation 'recv_SetCredentialAccessProfiles' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetCredentialAccessProfiles(_ns5__SetCredentialAccessProfilesResponse &ns5__SetCredentialAccessProfilesResponse);
        //
        /// Web service synchronous operation 'DeleteCredentialAccessProfiles' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCredentialAccessProfiles(_ns5__DeleteCredentialAccessProfiles *ns5__DeleteCredentialAccessProfiles, _ns5__DeleteCredentialAccessProfilesResponse &ns5__DeleteCredentialAccessProfilesResponse) { return this->DeleteCredentialAccessProfiles(NULL, NULL, ns5__DeleteCredentialAccessProfiles, ns5__DeleteCredentialAccessProfilesResponse); }
        /// Web service synchronous operation 'DeleteCredentialAccessProfiles' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteCredentialAccessProfiles(const char *soap_endpoint_url, const char *soap_action, _ns5__DeleteCredentialAccessProfiles *ns5__DeleteCredentialAccessProfiles, _ns5__DeleteCredentialAccessProfilesResponse &ns5__DeleteCredentialAccessProfilesResponse) { return this->send_DeleteCredentialAccessProfiles(soap_endpoint_url, soap_action, ns5__DeleteCredentialAccessProfiles) || this->recv_DeleteCredentialAccessProfiles(ns5__DeleteCredentialAccessProfilesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteCredentialAccessProfiles' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteCredentialAccessProfiles(const char *soap_endpoint_url, const char *soap_action, _ns5__DeleteCredentialAccessProfiles *ns5__DeleteCredentialAccessProfiles);
        /// Web service asynchronous operation 'recv_DeleteCredentialAccessProfiles' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteCredentialAccessProfiles(_ns5__DeleteCredentialAccessProfilesResponse &ns5__DeleteCredentialAccessProfilesResponse);
        //
        /// Web service synchronous operation 'GetWhitelist' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetWhitelist(_ns5__GetWhitelist *ns5__GetWhitelist, _ns5__GetWhitelistResponse &ns5__GetWhitelistResponse) { return this->GetWhitelist(NULL, NULL, ns5__GetWhitelist, ns5__GetWhitelistResponse); }
        /// Web service synchronous operation 'GetWhitelist' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetWhitelist(const char *soap_endpoint_url, const char *soap_action, _ns5__GetWhitelist *ns5__GetWhitelist, _ns5__GetWhitelistResponse &ns5__GetWhitelistResponse) { return this->send_GetWhitelist(soap_endpoint_url, soap_action, ns5__GetWhitelist) || this->recv_GetWhitelist(ns5__GetWhitelistResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetWhitelist' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetWhitelist(const char *soap_endpoint_url, const char *soap_action, _ns5__GetWhitelist *ns5__GetWhitelist);
        /// Web service asynchronous operation 'recv_GetWhitelist' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetWhitelist(_ns5__GetWhitelistResponse &ns5__GetWhitelistResponse);
        //
        /// Web service synchronous operation 'AddToWhitelist' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int AddToWhitelist(_ns5__AddToWhitelist *ns5__AddToWhitelist, _ns5__AddToWhitelistResponse &ns5__AddToWhitelistResponse) { return this->AddToWhitelist(NULL, NULL, ns5__AddToWhitelist, ns5__AddToWhitelistResponse); }
        /// Web service synchronous operation 'AddToWhitelist' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int AddToWhitelist(const char *soap_endpoint_url, const char *soap_action, _ns5__AddToWhitelist *ns5__AddToWhitelist, _ns5__AddToWhitelistResponse &ns5__AddToWhitelistResponse) { return this->send_AddToWhitelist(soap_endpoint_url, soap_action, ns5__AddToWhitelist) || this->recv_AddToWhitelist(ns5__AddToWhitelistResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_AddToWhitelist' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_AddToWhitelist(const char *soap_endpoint_url, const char *soap_action, _ns5__AddToWhitelist *ns5__AddToWhitelist);
        /// Web service asynchronous operation 'recv_AddToWhitelist' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_AddToWhitelist(_ns5__AddToWhitelistResponse &ns5__AddToWhitelistResponse);
        //
        /// Web service synchronous operation 'RemoveFromWhitelist' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int RemoveFromWhitelist(_ns5__RemoveFromWhitelist *ns5__RemoveFromWhitelist, _ns5__RemoveFromWhitelistResponse &ns5__RemoveFromWhitelistResponse) { return this->RemoveFromWhitelist(NULL, NULL, ns5__RemoveFromWhitelist, ns5__RemoveFromWhitelistResponse); }
        /// Web service synchronous operation 'RemoveFromWhitelist' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int RemoveFromWhitelist(const char *soap_endpoint_url, const char *soap_action, _ns5__RemoveFromWhitelist *ns5__RemoveFromWhitelist, _ns5__RemoveFromWhitelistResponse &ns5__RemoveFromWhitelistResponse) { return this->send_RemoveFromWhitelist(soap_endpoint_url, soap_action, ns5__RemoveFromWhitelist) || this->recv_RemoveFromWhitelist(ns5__RemoveFromWhitelistResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_RemoveFromWhitelist' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_RemoveFromWhitelist(const char *soap_endpoint_url, const char *soap_action, _ns5__RemoveFromWhitelist *ns5__RemoveFromWhitelist);
        /// Web service asynchronous operation 'recv_RemoveFromWhitelist' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_RemoveFromWhitelist(_ns5__RemoveFromWhitelistResponse &ns5__RemoveFromWhitelistResponse);
        //
        /// Web service synchronous operation 'DeleteWhitelist' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteWhitelist(_ns5__DeleteWhitelist *ns5__DeleteWhitelist, _ns5__DeleteWhitelistResponse &ns5__DeleteWhitelistResponse) { return this->DeleteWhitelist(NULL, NULL, ns5__DeleteWhitelist, ns5__DeleteWhitelistResponse); }
        /// Web service synchronous operation 'DeleteWhitelist' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteWhitelist(const char *soap_endpoint_url, const char *soap_action, _ns5__DeleteWhitelist *ns5__DeleteWhitelist, _ns5__DeleteWhitelistResponse &ns5__DeleteWhitelistResponse) { return this->send_DeleteWhitelist(soap_endpoint_url, soap_action, ns5__DeleteWhitelist) || this->recv_DeleteWhitelist(ns5__DeleteWhitelistResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteWhitelist' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteWhitelist(const char *soap_endpoint_url, const char *soap_action, _ns5__DeleteWhitelist *ns5__DeleteWhitelist);
        /// Web service asynchronous operation 'recv_DeleteWhitelist' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteWhitelist(_ns5__DeleteWhitelistResponse &ns5__DeleteWhitelistResponse);
        //
        /// Web service synchronous operation 'GetBlacklist' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetBlacklist(_ns5__GetBlacklist *ns5__GetBlacklist, _ns5__GetBlacklistResponse &ns5__GetBlacklistResponse) { return this->GetBlacklist(NULL, NULL, ns5__GetBlacklist, ns5__GetBlacklistResponse); }
        /// Web service synchronous operation 'GetBlacklist' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetBlacklist(const char *soap_endpoint_url, const char *soap_action, _ns5__GetBlacklist *ns5__GetBlacklist, _ns5__GetBlacklistResponse &ns5__GetBlacklistResponse) { return this->send_GetBlacklist(soap_endpoint_url, soap_action, ns5__GetBlacklist) || this->recv_GetBlacklist(ns5__GetBlacklistResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetBlacklist' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetBlacklist(const char *soap_endpoint_url, const char *soap_action, _ns5__GetBlacklist *ns5__GetBlacklist);
        /// Web service asynchronous operation 'recv_GetBlacklist' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetBlacklist(_ns5__GetBlacklistResponse &ns5__GetBlacklistResponse);
        //
        /// Web service synchronous operation 'AddToBlacklist' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int AddToBlacklist(_ns5__AddToBlacklist *ns5__AddToBlacklist, _ns5__AddToBlacklistResponse &ns5__AddToBlacklistResponse) { return this->AddToBlacklist(NULL, NULL, ns5__AddToBlacklist, ns5__AddToBlacklistResponse); }
        /// Web service synchronous operation 'AddToBlacklist' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int AddToBlacklist(const char *soap_endpoint_url, const char *soap_action, _ns5__AddToBlacklist *ns5__AddToBlacklist, _ns5__AddToBlacklistResponse &ns5__AddToBlacklistResponse) { return this->send_AddToBlacklist(soap_endpoint_url, soap_action, ns5__AddToBlacklist) || this->recv_AddToBlacklist(ns5__AddToBlacklistResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_AddToBlacklist' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_AddToBlacklist(const char *soap_endpoint_url, const char *soap_action, _ns5__AddToBlacklist *ns5__AddToBlacklist);
        /// Web service asynchronous operation 'recv_AddToBlacklist' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_AddToBlacklist(_ns5__AddToBlacklistResponse &ns5__AddToBlacklistResponse);
        //
        /// Web service synchronous operation 'RemoveFromBlacklist' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int RemoveFromBlacklist(_ns5__RemoveFromBlacklist *ns5__RemoveFromBlacklist, _ns5__RemoveFromBlacklistResponse &ns5__RemoveFromBlacklistResponse) { return this->RemoveFromBlacklist(NULL, NULL, ns5__RemoveFromBlacklist, ns5__RemoveFromBlacklistResponse); }
        /// Web service synchronous operation 'RemoveFromBlacklist' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int RemoveFromBlacklist(const char *soap_endpoint_url, const char *soap_action, _ns5__RemoveFromBlacklist *ns5__RemoveFromBlacklist, _ns5__RemoveFromBlacklistResponse &ns5__RemoveFromBlacklistResponse) { return this->send_RemoveFromBlacklist(soap_endpoint_url, soap_action, ns5__RemoveFromBlacklist) || this->recv_RemoveFromBlacklist(ns5__RemoveFromBlacklistResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_RemoveFromBlacklist' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_RemoveFromBlacklist(const char *soap_endpoint_url, const char *soap_action, _ns5__RemoveFromBlacklist *ns5__RemoveFromBlacklist);
        /// Web service asynchronous operation 'recv_RemoveFromBlacklist' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_RemoveFromBlacklist(_ns5__RemoveFromBlacklistResponse &ns5__RemoveFromBlacklistResponse);
        //
        /// Web service synchronous operation 'DeleteBlacklist' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteBlacklist(_ns5__DeleteBlacklist *ns5__DeleteBlacklist, _ns5__DeleteBlacklistResponse &ns5__DeleteBlacklistResponse) { return this->DeleteBlacklist(NULL, NULL, ns5__DeleteBlacklist, ns5__DeleteBlacklistResponse); }
        /// Web service synchronous operation 'DeleteBlacklist' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteBlacklist(const char *soap_endpoint_url, const char *soap_action, _ns5__DeleteBlacklist *ns5__DeleteBlacklist, _ns5__DeleteBlacklistResponse &ns5__DeleteBlacklistResponse) { return this->send_DeleteBlacklist(soap_endpoint_url, soap_action, ns5__DeleteBlacklist) || this->recv_DeleteBlacklist(ns5__DeleteBlacklistResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteBlacklist' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteBlacklist(const char *soap_endpoint_url, const char *soap_action, _ns5__DeleteBlacklist *ns5__DeleteBlacklist);
        /// Web service asynchronous operation 'recv_DeleteBlacklist' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteBlacklist(_ns5__DeleteBlacklistResponse &ns5__DeleteBlacklistResponse);
    };
#endif
